language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"

before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d

deploy:
  provider: gae
  keyfile: client-secret.json
  project: react-app-275712