language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - "$HOME/google-cloud-sdk/"

before_install:
- openssl aes-256-cbc -K $encrypted_d80a2d296111_key -iv $encrypted_d80a2d296111_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib

# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file client-secret.json
# [END auth]
install:
  # Set the correct project to deploy to
  - gcloud config set project demo-test
  # Install the Python dependencies
  - npm install

script:
  - npm test
  - npm run build
  - gcloud -q app deploy app.yaml --promote